//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Documents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Documents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocSite.Resources.Documents", typeof(Documents).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this document?.
        /// </summary>
        public static string DocumentDeleteConfirm {
            get {
                return ResourceManager.GetString("DocumentDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document deleted successfully.
        /// </summary>
        public static string DocumentDeleteSuccess {
            get {
                return ResourceManager.GetString("DocumentDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document saved successfully.
        /// </summary>
        public static string DocumentSavedSuccess {
            get {
                return ResourceManager.GetString("DocumentSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DocumentsTableDelete {
            get {
                return ResourceManager.GetString("DocumentsTableDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string DocumentsTableTitle {
            get {
                return ResourceManager.GetString("DocumentsTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string DocumentsTableUpdated {
            get {
                return ResourceManager.GetString("DocumentsTableUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Product.
        /// </summary>
        public static string IncorrectProduct {
            get {
                return ResourceManager.GetString("IncorrectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to records per page.
        /// </summary>
        public static string RecordsPerPage {
            get {
                return ResourceManager.GetString("RecordsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions.
        /// </summary>
        public static string Solutions {
            get {
                return ResourceManager.GetString("Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital books, online magazines, learning systems.
        /// </summary>
        public static string SolutionsHeader {
            get {
                return ResourceManager.GetString("SolutionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information technology is something we are good at, and we are happy to make this expertise available to our clients. Working together, we can find solutions that help you make the most of cutting-edge information technology..
        /// </summary>
        public static string SolutionsText {
            get {
                return ResourceManager.GetString("SolutionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeBase.
        /// </summary>
        public static string TimeBase {
            get {
                return ResourceManager.GetString("TimeBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your material.
        /// </summary>
        public static string TimeBaseHeader {
            get {
                return ResourceManager.GetString("TimeBaseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your material anywhere, anytime.You can use Microsoft Word, Open Office, Adobe FrameMaker, Adobe InDesign, a free XML editor or an Internet browser to edit text. TimeBase is an editor’s tool that is always at the ready.
        ///            TimeBase provides a secure location for storing your material.A centralised system makes it easy to use the material for a variety of products and projects - also enabling the automatic creation of daily backup copies.
        ///            Various tools can be integrated into the T [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TimeBaseText {
            get {
                return ResourceManager.GetString("TimeBaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimePub.
        /// </summary>
        public static string TimePub {
            get {
                return ResourceManager.GetString("TimePub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-channel publishing.
        /// </summary>
        public static string TimePubHeader {
            get {
                return ResourceManager.GetString("TimePubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        public static string TimePubLi1 {
            get {
                return ResourceManager.GetString("TimePubLi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing or incoming links.
        /// </summary>
        public static string TimePubLi2 {
            get {
                return ResourceManager.GetString("TimePubLi2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of contents.
        /// </summary>
        public static string TimePubLi3 {
            get {
                return ResourceManager.GetString("TimePubLi3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string TimePubLi4 {
            get {
                return ResourceManager.GetString("TimePubLi4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string TimePubLi5 {
            get {
                return ResourceManager.GetString("TimePubLi5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concept map.
        /// </summary>
        public static string TimePubLi6 {
            get {
                return ResourceManager.GetString("TimePubLi6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor’s picks.
        /// </summary>
        public static string TimePubLi7 {
            get {
                return ResourceManager.GetString("TimePubLi7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same material can be turned into a variety of products and services for different platforms. In electronic publishing, a responsive website can cater for a wide range of devices including PCs, mobile phones and tablets; while layout software, such as Indesign, Adobe FrameMaker, MS Word, Open Office, can be used to produce print publications.
        ///Users can navigate through an electronic publication using:.
        /// </summary>
        public static string TimePubText {
            get {
                return ResourceManager.GetString("TimePubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeShop.
        /// </summary>
        public static string TimeShop {
            get {
                return ResourceManager.GetString("TimeShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our online store platform.
        /// </summary>
        public static string TimeShopHeader {
            get {
                return ResourceManager.GetString("TimeShopHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeShop is an innovative online store solution ideal for large and medium-sized companies operating nationally or internationally.
        ///            TimeShop is much more than a shopping basket and an e-payment system. Our online store platform can be used to its full potential by integrating it with customer relationship management and marketing systems. Product delivery can also be automated for extra efficiency..
        /// </summary>
        public static string TimeShopText {
            get {
                return ResourceManager.GetString("TimeShopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to delete public documents..
        /// </summary>
        public static string UnauthorizedDelete {
            get {
                return ResourceManager.GetString("UnauthorizedDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Documents.
        /// </summary>
        public static string UploadDocuments {
            get {
                return ResourceManager.GetString("UploadDocuments", resourceCulture);
            }
        }
    }
}
